import type { ContentItem } from './content-repository';

export const demoContent: ContentItem[] = [
  { id:'1', title:'Designing an API that ages well', excerpt:'Contracts, compatibility, and production-safe evolution.', kind:'article', status:'draft', series:'API Field Guide', seriesSlug:'api-field-guide', tags:[{name:'API design',slug:'api-design',color:'#7757ff'},{name:'.NET',slug:'dotnet',color:'#3585d3'}], updatedAt:'2026-08-30T08:42:00Z', publishedAt:null, scheduledAt:null, viewCount:0, popularityScore:0, coverUrl:null },
  { id:'2', title:'Generate PDF invoices in ASP.NET Core', excerpt:'A production-ready invoice pipeline with QuestPDF and clean boundaries.', kind:'article', status:'published', series:'ASP.NET Core in Production', seriesSlug:'aspnet-production', tags:[{name:'.NET',slug:'dotnet',color:'#3585d3'},{name:'PDF',slug:'pdf',color:'#d35f35'}], updatedAt:'2026-08-28T13:10:00Z', publishedAt:'2026-08-25T09:00:00Z', scheduledAt:null, viewCount:12840, popularityScore:94.2, coverUrl:null },
  { id:'3', title:'The quiet architecture of reliable jobs', excerpt:'Idempotency, retries, and observable background work.', kind:'post', status:'review', series:'Systems Notes', seriesSlug:'systems-notes', tags:[{name:'Architecture',slug:'architecture',color:'#45a36b'}], updatedAt:'2026-08-29T16:25:00Z', publishedAt:null, scheduledAt:null, viewCount:0, popularityScore:0, coverUrl:null },
  { id:'4', title:'Shipping an Astro knowledge base', excerpt:'Content collections, MDX, search, and a Git-native release flow.', kind:'article', status:'scheduled', series:'Build XStudio', seriesSlug:'build-xstudio', tags:[{name:'Astro',slug:'astro',color:'#e05e8b'},{name:'MDX',slug:'mdx',color:'#7757ff'}], updatedAt:'2026-08-27T11:40:00Z', publishedAt:null, scheduledAt:'2026-09-02T07:30:00Z', viewCount:0, popularityScore:0, coverUrl:null },
  { id:'5', title:'Schema-first editing without lock-in', excerpt:'Why the canonical document sits between Tiptap and MDX.', kind:'article', status:'published', series:'Build XStudio', seriesSlug:'build-xstudio', tags:[{name:'Tiptap',slug:'tiptap',color:'#8f6a35'},{name:'MDX',slug:'mdx',color:'#7757ff'}], updatedAt:'2026-08-22T10:00:00Z', publishedAt:'2026-08-20T10:00:00Z', scheduledAt:null, viewCount:8640, popularityScore:88.7, coverUrl:null },
  { id:'6', title:'Notes on naming things', excerpt:'A short field note on names that survive changing requirements.', kind:'post', status:'trash', series:null, seriesSlug:null, tags:[{name:'Writing',slug:'writing',color:'#55606f'}], updatedAt:'2026-08-12T10:00:00Z', publishedAt:null, scheduledAt:null, viewCount:0, popularityScore:0, coverUrl:null },
];
